[tool.commitizen]
version = "1.0.1"
bump_message = "chore(release): $current_version -> $new_version [skip-ci]"
version_files = [
#    "./TemplatePlugin/Properties/AssemblyInfo.cs", # Enable this 
    ".nuspec" # Remove this
]
tag_format = "v$version"