name: Release

on: 
  push:
    branches:
      - main

jobs:
  release:
    if: "!endsWith(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ubuntu-latest
    name: "Bump version, create changelog with commitizen and create release"
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog_increment_filename: body.md
          branch: main
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "body.md"
          tag_name: v${{ env.REVISION }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
