name: NuGet

on:
  push:
    tags:
      - 'v*'

jobs:
  pack:
    runs-on: windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          path: './'
          fetch-depth: 0
      - name: Add nuget
        uses: nuget/setup-nuget@v1

      - name: Pack
        run: nuget pack -NoDefaultExcludes

      - name: Push
        shell: bash
        env:
          NUGET_KEY: ${{ secrets.NUGET }}
        run: nuget push ./*.nupkg -NonInteractive -src https://api.nuget.org/v3/index.json -ApiKey $NUGET_KEY