name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    if: "!endsWith(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ubuntu-latest
    name: "Bump version, create changelog with commitizen and create release"
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog_increment_filename: body.md
          branch: main
      - name: Add nuget
        uses: nuget/setup-nuget@v1

      - name: Pack
        run: nuget pack -NoDefaultExcludes

      - name: Push
        shell: bash
        env:
          NUGET_KEY: ${{ secrets.NUGET }}
        run: nuget push ./*.nupkg -NonInteractive -src https://api.nuget.org/v3/index.json -ApiKey $NUGET_KEY
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "body.md"
          tag_name: v${{ env.REVISION }}
          files: |
            *.nupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
